[build]
  command = "npm install && npm run build"
  functions = "functions"
  environment = { PRIV_KEY = "-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEAvcBPZ3hv2n5sWojJHmcwg/9qJejwzQnDMb6gM/P0gVjnYF81
ZlqIYmS909kkHZ34GdZekG22aqK6RWwNH41SLS+TIq8CUpt3hWW4cGNwLKzafhnB
DeZrR1tzBPKQMTa1gNJnmwDx/4QcMthyMa981fSurII+XxSJzBzc7ecxYIvdMPlx
jurwc4po0ngl20K4CypGjKZPoblsw3FWsRh/K0N8PXS34jgiRRh8VL8AukBfZgyn
t59WjtJhjSqc1tEJ41nYn4nWnqPLWmH1mjZZDvWYFoUlJto2e2n5jA/yuw9zKT6p
yC1XKcPnjqL+7llsGOF6UE92mWPdvRsS4VN5FxUscsxoZ+M7MPAAPFSVxD/WQrPd
iO63I5ys4F9fPTPk+VZXY6bLroWHlS6idjGWMJ1RCB4YAhBFd6KVdcui2MD9JjsM
Pbn3SwAnsvy5RL/L8Rj1qfp93xuaZeTIUaKs9oGA0qN+ym30JLi2RnsyUQi4MPFg
d0aFUmx5ktAdWZG1lVocwdE0pNQjfeMgAoNYEQB+au6sTtG+rV4vdi9mfWBiUuZ3
HdyWxatI7if6cNQnUIa8Rc0loyKkbfWk9Olq4RMWKsFH9iktzZ+RGpoHpQTzna4z
yLT0zGIngoEyEnCwjtx+rVWrC75ZYwtJoDwoN3epgRMTRi+zExnpanxgb18CAwEA
AQKCAgBGIu82r62odVJXpHeyZTHpmF8D5DYdk54ypONSULnvlYzwckCqtIv00ofX
5ksTJ3CtHC+X8vWaNMvlHSs8nl/hk9Qu3cFeB1kGVbL218p+uOWJ9rsFCEZe+c5p
5b6mcjJki2EASjko2QwTPy32b4cVDnwCB6JGQrEsYP7IcMwvg4MetxTiXrTCAEb+
hKp5gQ/GELpDArYscP1iwGHq08MtmqQxkxLk6xq/r21FZdQ/A8w/TC4yERNNdzXX
mAig3mNpRaxsS+aofKKNpefCOJRykxTEPjKdScsZkvJKcxqlSfCnLiJTe27cYS0V
6+mO8D6kc7NiO/z6dY9gdsFjyBbZbmW1Zzxzf5pH00Kwb7xN42LZiuWvld1yHhtC
z+t6MswoETs/4HdvAQCk9XHXrJr/ayNxatJsWSCh4pNrzjLB97pwD9LAsdqNOpi9
1aW4l/J++7vk3LdiYrhcVnGs9mvKhlwI6UpUhL8eiVJ3UV0QqrY8kwxWHnZmh52U
CQjb2JkTNW9DYmH4vXfBjrydTyb3OuialnQSqvC20McwMkgei6pfSr/+HpJP+60s
c8TemX+Q47XiSkw6QMShEysDIbVH0Ovyz4hiae6S0B6XnhOpwfPid7NnkW8BOhcI
tmUOF4vm14t0w5UU65Ri5328CdtAnWNlS3ehYEdfQr8pdZfYAQKCAQEA4A7aXXu5
y0HG6M+UULJeDzk3MAM6titTBWyPrV49bCms9gHiAID1we53aKdzlSoU7Y/xis2E
B4JeRPfREtP+GcpIEobHfo8C5IiainCRLw8kd68lvZnUrPy71H+m7Jlb9vEXoVIH
wnEnHRdgYjDvtXqSX129vJRdkrQoPaWkPHxp/Apgy+wTvkCVILaHeNZmPUjr5Uum
ZKq1vV+vuq3DdBVFr+9QTTF13YTLHpFhuVEeRPCa5pH0taMxZhToqXEAFYorQ0R6
x/Ao945ZmB0Zy1zwl5X+gzl5SWDaKTvlnk50sdYRbOKezyKVBWNcvP+J4Q8EtgTp
IILjNvooIY3eIQKCAQEA2M1oRn4m3VLz3Hf4+6MrsER5nY/3BKrXvVLnvgb6ucyZ
gh3dV0ATIyMHjvRyOdDCATmD/nPX3gO+XLba0ChM2JxL9Ra0Edyfz3fyayUK1vYM
Do+OdhUV/g72rF+gevjgsLTEwmTrxKrcYJkknrVE1grQ3FC/LHjZ0UX4Msvc4lw3
DOIYdtq18+Ty1gutpKuIljuxxeznrPUstMkAWmzL+bvbna6Zfv1Wa2L+gPEmdM+p
Qr0QA4G1unWMy6Flu32q0QlsGEXpxSljEFLR85fyI/hc0WWpAHUf75mmgsO9QmIe
hsmey0HpCdTrJluS41nw9pp1Gs5P9LfNCCaXWyWdfwKCAQBZYZN694CGtRbEiQqB
pqYfLJP3c1JYma/k2gn2/0FBhN6axOWDje58DsVT2nkhaEgw/Ns+o/2ngTpaCQI+
oJMddrSJr3ql4iclQ9lioMVKIKBLnnNPz64n1CqZ+tJ8UDF/sW3bzP2Lc9hGoqyw
fxUhMGRz5tFqCUXK4FOtRAbgmkEtanZy4xp9KwZSpn4klmLyz8RLFIKsZe1aPnG7
5tWx2UqThMRkBvceB3uAFj8FznZkyhcBI/ia/R8Xuf+WmJ2P+i6IBylz2Tp+hyr2
o6VGmyzfS9bcQnE/9IMTL/HJ1UJ4Lw2EgmMX/pO0Mo8sVkSKo5MdiZf2gEBkDic0
O4QBAoIBAFgZB+F1S8et+KhDHCrtAEjNWnn7UU5VOfuV39OpNGMhz9M+3X2h7OTf
TCf8DxqNSPiEba2NV0/BR66XI01owulWgcsjIaMMeugsfpapY8E8FGQqU6KKKPin
Dfe3mBfAYFWN71Jq/h9ZqtmaAXZ4hHNRy9NrAHRK24AdpaDGlIhrHneevIA3ma50
/3SZJEOA7KzXrwKVpQL0UelYsEsOYMinXLOzim4+9coHXRH6bD0VUVtsRkCWicku
ETuB5zwL8cilwoYOitLyYW31qZkJynxxZQ41+DnWXlbXogELFzINewgcj+labB7x
pWhd18+I8dDTrPhqk7UGp0tDm0ePfnMCggEAcKMcWsNX1a6m2eYMHTQlzdr4fPmJ
s81+T8yafMcBkvw2OAv3jh+SPC+OVdjlVA1ZwwKtWljItQweDmbYP+rk0WYe5LjB
+zNA5CjszGFS1v6k9YTY8EAlpFgDrId4HqukKg+57AHdIm946OM7rG43S2HBMVTM
NjceYwycsko+LtChV8Ose6113BPE9zoS2xZW4oWHACPpC8V8ScYxlv4Qu+IvLOvS
aBFRFmf6Umf3O98UYFLgwNUAlG4IJtZ8ttpEDu4j774ggi+WepmXKXw4MsWN1Dm1
uRp2zvWgFpzQw0zLCM8TYVUr9gcpWCJEmWD8d9T3y4IJnTAlvC4BpVsfgA==
-----END RSA PRIVATE KEY-----" }
